# Start from the latest Ubuntu image
FROM ubuntu:latest

# Set the non-interactive mode for tzdata (prevents the interactive timezone query)
ENV DEBIAN_FRONTEND=noninteractive

# Update the system and install necessary software
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip to the latest version
RUN pip3 install --upgrade pip

RUN pip install jupyter openai scikit-llm scikit-learn matplotlib numpy pandas seaborn

# Set up the working directory
RUN mkdir /workspace
WORKDIR /workspace

# Change the ownership and permissions of /.local and /workspace
RUN mkdir /.local /.jupyter
RUN chmod -R 777 /.local /.jupyter /workspace

# When the container launches, start a Jupyter Notebook server
CMD ["jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser"]

